version: "3"
services:
  tests:
    build: .
    volumes:
      - .:/code
    command: >
      bash -c "python bin/init.py &&
               pytest -p no:cacheprovider -vv tests/"
    depends_on:
      - postgres
      - memcached
    links:
      - postgres
      - memcached
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=crash
      - POSTGRES_PASSWORD=stop
      - POSTGRES_DB=crashstop
    expose:
      - 5432
  memcached:
    image: memcached
    expose:
      - 11211
